name: genai
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - faiss-cpu
  - streamlit
  - pypdf
  - lxml
  - openssl
  - sqlite
  - libffi
  - zlib
  - cffi
  - libpython
  - wheel
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - jupyterlab
  - ipywidgets
  - notebook
  - matplotlib-inline
  - pyzmq
  - tk
  - tbb
  - libprotobuf
  - grpc-cpp
  - abseil-cpp

  - pip:
      # 🔹 Core LangChain (new >=0.2.2 required for huggingface module split)
      - langchain>=0.2.2
      - langchain-core>=0.2.0
      - langchain-community>=0.2.0
      - langchain-openai>=0.1.7

      - langchain-huggingface>=0.0.5

      # 🔹 Embeddings & Models
      - sentence-transformers
      - huggingface-hub
      - transformers

      # 🔹 Data Loaders & Preprocessors
      - unstructured
      - html5lib
      - beautifulsoup4
      - pypdf

      # 🔹 Streamlit & Enhancements
      - streamlit-chat
      - python-dotenv

      # 🔹 Groq/OpenAI Compatible Clients
      - openai

      # 🔹 Performance & Utils
      - tqdm
      - requests
      - regex
      - rich
      - aiohttp
      - tiktoken

      # 🔹 FastAPI (only if you're using API interfaces)
      - fastapi
      - uvicorn

      # 🔹 Pydantic for validation
      - pydantic>=2.7.1
      - pydantic-settings>=2.2.1
